#!/usr/bin/env python3
"""Rebuild every figure and table the paper uses, and record where each came from.

One command, so that the code-availability statement is something a reader can
run rather than something they have to take on trust. Figures are written
without an embedded timestamp (see `figstyle.py`), so a rebuild that changes
nothing produces no diff.

    python3 make_all.py             # check the record, rebuild, write provenance
    python3 make_all.py --skip-check    # rebuild without checking the record first
    python3 make_all.py --no-paper      # leave the paper tree alone

The record check runs first and stops the rebuild on failure. A figure built
from an incomplete record is worse than no figure, because it looks finished.
"""

import argparse
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

import reported

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
FIGURES = REPO / "figures"
PAPER = Path.home() / "Workplace/papers/richards-morrow-2026"

# (script, what it produces). Figures land in figures/, tables in the paper's
# Tables/ directory.
STEPS = [
    ("plot_paper_figures.py", [
        "Cockett2018/cockett_scaling.pdf",
        "Murrumbidgee/weak_scaling.pdf",
        "Murrumbidgee/strong_scaling.pdf",
    ]),
    ("plot_seasonal_figures.py", [
        "Murrumbidgee/seasonal_weak.pdf",
        "Murrumbidgee/seasonal_saturated.pdf",
        "Murrumbidgee/seasonal_breakdown.pdf",
    ]),
    ("make_tables.py", ["Tables/solver_outcomes.tex"]),
    ("make_performance_table.py", ["Tables/solver_performance.tex"]),
    ("make_seasonal_table.py", ["Tables/seasonal_scaling.tex"]),
    ("compute_dcol.py", ["Tables/dcol.tex"]),
]

# Which parsed experiments each output is built from.
SOURCES = {
    "Cockett2018/cockett_scaling.pdf": ["cockett"],
    "Murrumbidgee/weak_scaling.pdf": ["murr_horizontal", "murr_vertical"],
    "Murrumbidgee/strong_scaling.pdf": ["murr_strong"],
    "Murrumbidgee/seasonal_weak.pdf": ["murr_seasonal"],
    "Murrumbidgee/seasonal_saturated.pdf": ["murr_seasonal_saturated"],
    "Murrumbidgee/seasonal_breakdown.pdf": ["murr_seasonal"],
    "Tables/solver_outcomes.tex": list(reported.EXPERIMENTS),
    "Tables/solver_performance.tex": [
        "cockett", "murr_horizontal", "murr_vertical", "murr_seasonal"],
    "Tables/seasonal_scaling.tex": ["murr_seasonal"],
    "Tables/dcol.tex": [],   # computed from murrumbidgee_data/, not from runs
}

ARGS = {
    "make_tables.py": ["--outdir", str(PAPER / "Tables")],
    "make_performance_table.py": ["-o", str(PAPER / "Tables/solver_performance.tex")],
    "make_seasonal_table.py": ["--outdir", str(PAPER / "Tables")],
    "compute_dcol.py": ["--latex", "--outdir", str(PAPER / "Tables")],
}

COMMIT = re.compile(r"G-ADOPT commit: ([0-9a-f]{40})")


def run(script, extra=()):
    cmd = [sys.executable, str(HERE / script), *ARGS.get(script, []), *extra]
    print(f"--- {script}")
    result = subprocess.run(cmd, cwd=HERE, capture_output=True, text=True)
    if result.returncode != 0:
        print(result.stdout[-2000:])
        print(result.stderr[-2000:], file=sys.stderr)
        raise SystemExit(f"{script} failed")
    return result


def gadopt_commits():
    """The g-adopt commits the reported runs were produced with."""
    seen = {}
    for experiment in reported.EXPERIMENTS.values():
        for preset in reported.presets_for(experiment.key):
            for scale in experiment.scales:
                out = HERE / "results" / experiment.key.replace(
                    "murr_horizontal", "murr_horiz").replace(
                    "murr_vertical", "murrumbidgee")
                path = out / preset.key / f"{scale}.out"
                if not path.exists():
                    continue
                head = path.read_text(errors="ignore")[:4000]
                match = COMMIT.search(head)
                if match:
                    seen.setdefault(preset.key, {}).setdefault(
                        match.group(1), 0)
                    seen[preset.key][match.group(1)] += 1
    return seen


def provenance():
    lines = [
        "# Provenance",
        "",
        "Generated by `make_all.py`; do not edit. Every figure and table the",
        "manuscript uses, with the script that builds it and the parsed",
        "experiments it is built from.",
        "",
        f"Rebuilt {date.today().isoformat()}.",
        "",
        "| Output | Built by | From |",
        "|---|---|---|",
    ]
    for script, outputs in STEPS:
        for out in outputs:
            sources = SOURCES.get(out, [])
            src = ", ".join(f"`parsed/{s}.json`" for s in sources) or \
                "`murrumbidgee_data/`"
            lines.append(f"| `{out}` | `{script}` | {src} |")

    commits = gadopt_commits()
    lines += ["", "## G-ADOPT commit behind each reported preset", ""]
    if not commits:
        lines.append("No run output found to read a commit from.")
    else:
        lines.append("| Preset | Commit | Runs |")
        lines.append("|---|---|---|")
        for key in (p.key for p in reported.ALL_REPORTED):
            for sha, count in sorted(commits.get(key, {}).items(),
                                     key=lambda kv: -kv[1]):
                lines.append(f"| `{key}` | `{sha[:12]}` | {count} |")
        lines += [
            "",
            "The lumped presets and the baselines are not expected to share a",
            "commit. The 2026-08-29 change to the solver source removed the",
            "lagged operator snapshot and added the measured Richardson",
            "damping, both of which live in `VerticallyLumpedPC`,",
            "`VerticallyLumpedHMGPC` and the `vlumping*` preset dictionaries.",
            "`bjacobi`, `gmg`, `sor`, `gamg` and `boomeramg` are configured",
            "from option dictionaries in this repository and touch none of",
            "that code, so re-running them against the newer source would",
            "reproduce the same numbers at considerable cost.",
            "",
            "Two commits *within* one preset is a different matter and means",
            "that preset's runs are not all from one solver source.",
        ]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--skip-check", action="store_true")
    ap.add_argument("--no-paper", action="store_true")
    args = ap.parse_args()

    if not args.skip_check:
        print("--- check_record.py")
        check = subprocess.run(
            [sys.executable, str(HERE / "check_record.py")],
            cwd=HERE, capture_output=True, text=True)
        print(check.stdout[-3000:])
        if check.returncode != 0:
            raise SystemExit(
                "the record does not support every reported number; fix that "
                "or rerun with --skip-check if you know why")

    for script, _ in STEPS:
        if args.no_paper and script in ARGS:
            continue
        run(script)

    # The plotters write into figures/; the manuscript reads Figures/. Copying
    # is part of the rebuild, not a separate thing to remember. Leaving it
    # manual is how the paper tree ended up holding pre-campaign figures while
    # the repository held the new ones.
    if not args.no_paper:
        copied = 0
        for _, outputs in STEPS:
            for rel in outputs:
                if not rel.endswith(".pdf"):
                    continue
                src, dst = FIGURES / rel, PAPER / "Figures" / rel
                if not src.exists():
                    raise SystemExit(f"{src} was not produced")
                dst.parent.mkdir(parents=True, exist_ok=True)
                if not dst.exists() or dst.read_bytes() != src.read_bytes():
                    dst.write_bytes(src.read_bytes())
                    copied += 1
        print(f"\ncopied {copied} figure(s) into {PAPER / 'Figures'}")

    target = HERE / "PROVENANCE.md"
    target.write_text(provenance())
    print(f"\nWrote {target}")


if __name__ == "__main__":
    main()
