"""Composite ParaView render of the Lower Murrumbidgee demo solution.

Reads the Richards-equation demo output (PressureHead, SaturatedConductivity and
depth on the terrain-following extruded basin, written by murrumbidgee_demo.py)
and builds, in one scene:
  * the basin with the z-axis exaggerated (the horizontal extent dwarfs the
    vertical, so without exaggeration it reads as a flat sheet);
  * the mesh welded (CleantoGrid) to merge Firedrake's per-cell duplicated DG
    vertices, so the transparent surfaces show no partition seams;
  * the conductivity body (log SaturatedConductivity, Inferno) split in x: the
    camera-side half made very transparent to expose the interior, the far half
    kept for context with its Ks cross-section on the cut face;
  * the land surface as a smooth, classic topography (gist_earth) lid;
  * the water table as the PressureHead = 0 isosurface (blue);
  * Darcy-flux glyphs q = -K grad(z + h) through the saturated zone (h >= 0);
  * town markers (Hay, Narrandera, Balranald) with labels.

The raw .vtu/.pvtu are kept locally (git-ignored) under demo_output/; the
finished PNG is written into the paper figures/ tree and is regenerated by
re-running this script.

Run SERIAL (the global point-weld must happen in one process):
    ~/Workplace/ParaView-install/bin/pvbatch viz_murrumbidgee.py
"""

import os

from paraview.simple import *

# ----------------------------------------------------------------------------
# Parameters
# ----------------------------------------------------------------------------
_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_HERE)

ZEX = 150.0                      # vertical exaggeration
INDEX = 0                        # output index (_0 or _1)
DATA = os.path.join(_HERE, "demo_output", "murrumbidgee_demo",
                    "murrumbidgee_demo_%d.pvtu" % INDEX)   # kept local, git-ignored
OUT = os.path.join(_REPO, "figures", "Murrumbidgee", "example_solution.png")
RES = [2400, 1500]

# domain bounds (from probe)
XMIN, XMAX = 45000.0, 325000.0
YMIN, YMAX = 73800.0, 203800.0
YMID = 0.5 * (YMIN + YMAX)

# ----------------------------------------------------------------------------
# Load + exaggerate
# ----------------------------------------------------------------------------
reader = OpenDataFile(DATA)

# Weld the mesh: Firedrake writes per-cell duplicated vertices (DG layout), so
# the .pvtu has ~32.5M points for 4.68M cells.  Rendered transparent, every
# piece/partition boundary then shows as a seam.  Merging coincident points
# (-> ~2.4M unique) makes the grid watertight, so the surface shows only the
# true outer boundary.  This must be global, hence the serial (non-MPI) run.
clean = CleantoGrid(Input=reader)

xform = Transform(Input=clean)
xform.Transform.Scale = [1.0, 1.0, ZEX]

view = GetActiveViewOrCreate('RenderView')
view.ViewSize = RES
view.OrientationAxesVisibility = 0
view.Background = [1.0, 1.0, 1.0]

# ----------------------------------------------------------------------------
# Interior: SaturatedConductivity, log scale
# ----------------------------------------------------------------------------
# Split the domain in x (the long axis) at the mid-plane so the water table
# reads: the near (camera-side, low x / west) half is made very transparent to
# expose the water-table surface, while the far half keeps the conductivity
# context and shows the Ks cross-section on its cut face.
SPLIT_X = 0.5 * (XMIN + XMAX)
NEAR_OPACITY = 0.2
FAR_OPACITY = 0.5

nearBody = Clip(Input=xform)
nearBody.ClipType = 'Plane'
nearBody.ClipType.Origin = [SPLIT_X, 0.0, 0.0]
nearBody.ClipType.Normal = [1.0, 0.0, 0.0]     # keep x < SPLIT_X (camera side)

farBody = Clip(Input=xform)
farBody.ClipType = 'Plane'
farBody.ClipType.Origin = [SPLIT_X, 0.0, 0.0]
farBody.ClipType.Normal = [1.0, 0.0, 0.0]
farBody.Invert = 0                              # keep x > SPLIT_X

ksLUT = GetColorTransferFunction('SaturatedConductivity')
ksLUT.UseLogScale = 1
ksLUT.RescaleTransferFunction(1.0e-7, 5.0e-4)
ksLUT.ApplyPreset('Inferno', True)

for _half, _op in [(nearBody, NEAR_OPACITY), (farBody, FAR_OPACITY)]:
    _bd = Show(_half, view)
    ColorBy(_bd, ('POINTS', 'SaturatedConductivity'))
    _bd.Opacity = _op

ksBar = GetScalarBar(ksLUT, view)
ksBar.Title = 'Saturated conductivity [m/s]'
ksBar.ComponentTitle = ''
ksBar.TitleColor = [0, 0, 0]
ksBar.LabelColor = [0, 0, 0]
ksBar.Orientation = 'Horizontal'
ksBar.WindowLocation = 'Any Location'
ksBar.Position = [0.58, 0.22]
ksBar.ScalarBarLength = 0.28
ksBar.ScalarBarThickness = 32
ksBar.TitleFontFamily = 'Times'
ksBar.LabelFontFamily = 'Times'
ksBar.TitleFontSize = 33
ksBar.LabelFontSize = 29
ksBar.UseCustomLabels = 1
ksBar.CustomLabels = [1e-6, 1e-5, 1e-4]
ksBar.AddRangeLabels = 0

# ----------------------------------------------------------------------------
# Topography lid: top surface coloured by elevation
# ----------------------------------------------------------------------------
surf = ExtractSurface(Input=xform)
topThr = Threshold(Input=surf)
topThr.Scalars = ['POINTS', 'depth']
topThr.LowerThreshold = -1.0
topThr.UpperThreshold = 1.0
topThr.ThresholdMethod = 'Between'

elev = Calculator(Input=topThr)
elev.ResultArrayName = 'elevation'
elev.Function = 'coordsZ / %g' % ZEX          # report true metres
elev.AttributeType = 'Point Data'

# Lift the opaque lid a hair above the body's top face, otherwise the two
# coincide and z-fight -- the body's Inferno top wins and the elevation colour
# never shows (changing the elevation colormap then appears to do nothing).
lidx = Transform(Input=elev)
lidx.Transform.Translate = [0.0, 0.0, 600.0]

# smooth shading: compute point normals so the surface is not faceted
lidpoly = ExtractSurface(Input=lidx)
lidnorm = SurfaceNormals(Input=lidpoly)
lidnorm.Splitting = 0

topo = Show(lidnorm, view)
topo.Opacity = 1.0           # topography fully visible
ColorBy(topo, ('POINTS', 'elevation'))
elevLUT = GetColorTransferFunction('elevation')
# classic topography (DEM) colormap: green lowlands -> tan/brown uplands.
elevLUT.ApplyPreset('gist_earth', True)
elevLUT.RescaleTransferFunction(40.0, 220.0)
elevBar = GetScalarBar(elevLUT, view)
elevBar.Title = 'Surface Elevation [m]'
elevBar.ComponentTitle = ''
elevBar.TitleColor = [0, 0, 0]
elevBar.LabelColor = [0, 0, 0]
elevBar.Orientation = 'Horizontal'
elevBar.WindowLocation = 'Any Location'
elevBar.Position = [0.58, 0.32]
elevBar.ScalarBarLength = 0.28
elevBar.ScalarBarThickness = 32
elevBar.TitleFontFamily = 'Times'
elevBar.LabelFontFamily = 'Times'
elevBar.TitleFontSize = 33
elevBar.LabelFontSize = 29
elevBar.UseCustomLabels = 1
elevBar.CustomLabels = [60.0, 110.0, 160.0]
elevBar.AddRangeLabels = 0

# ----------------------------------------------------------------------------
# Water table: isosurface of PressureHead = 0.  Below it the soil is saturated
# (h > 0), above it unsaturated (h < 0).
# ----------------------------------------------------------------------------
wt = Contour(Input=xform)
wt.ContourBy = ['POINTS', 'PressureHead']
wt.Isosurfaces = [0.0]
wtDisp = Show(wt, view)
# colour by PressureHead with a constant-blue LUT so we get a blue legend swatch
ColorBy(wtDisp, ('POINTS', 'PressureHead'))
wtLUT = GetColorTransferFunction('PressureHead')
wtLUT.RGBPoints = [-1.0, 0.05, 0.25, 1.0, 1.0, 0.05, 0.25, 1.0]   # constant blue
wtDisp.Opacity = 0.7

# blue swatch + label, to the LEFT of the other colorbars
wtBar = GetScalarBar(wtLUT, view)
wtBar.Title = 'Water table (h = 0)'
wtBar.ComponentTitle = ''
wtBar.TitleColor = [0, 0, 0]
wtBar.Orientation = 'Horizontal'
wtBar.WindowLocation = 'Any Location'
wtBar.Position = [0.40, 0.27]
wtBar.ScalarBarLength = 0.12
wtBar.ScalarBarThickness = 32
wtBar.TitleFontFamily = 'Times'
wtBar.TitleFontSize = 33
wtBar.DrawTickLabels = 0
wtBar.DrawTickMarks = 0
wtBar.AddRangeLabels = 0

# ----------------------------------------------------------------------------
# Darcy-flux glyphs through the whole volume.  q = -K grad(H), H = z + h,
# K ~ SaturatedConductivity, computed on the welded grid in TRUE coordinates;
# the z-component of the *display* vector is stretched by ZEX and the geometry
# moved into the exaggerated scene with a Transform that leaves the vector
# untouched.  Arrows are sampled evenly through the volume interior.
# ----------------------------------------------------------------------------
H = Calculator(Input=clean)
H.ResultArrayName = 'H'
H.Function = 'coordsZ + PressureHead'
H.AttributeType = 'Point Data'

grad = Gradient(Input=H)
grad.ScalarArray = ['POINTS', 'H']
grad.ResultArrayName = 'gradH'

flux = Calculator(Input=grad)
flux.ResultArrayName = 'flux'
flux.Function = ('(-SaturatedConductivity*gradH_X)*iHat'
                 ' + (-SaturatedConductivity*gradH_Y)*jHat'
                 ' + (-%g*SaturatedConductivity*gradH_Z)*kHat' % ZEX)
flux.AttributeType = 'Point Data'

# compressed magnitude for arrow length: |q| spans ~6 orders, so a power law
# keeps small fluxes visible while still growing arrows with flux strength.
fscale = Calculator(Input=flux)
fscale.ResultArrayName = 'fscale'
fscale.Function = 'mag(flux)^0.2'
fscale.AttributeType = 'Point Data'

fluxx = Transform(Input=fscale)
fluxx.Transform.Scale = [1.0, 1.0, ZEX]
fluxx.TransformAllInputVectors = 0        # move geometry only, keep vectors as is

# keep only the saturated zone (below the water table, PressureHead >= 0) so
# the arrows appear only where there is meaningful flow
sat = Threshold(Input=fluxx)
sat.Scalars = ['POINTS', 'PressureHead']
sat.LowerThreshold = 0.0
sat.UpperThreshold = 1.0e6
sat.ThresholdMethod = 'Between'

glyph = Glyph(Input=sat, GlyphType='Arrow')
glyph.OrientationArray = ['POINTS', 'flux']       # arrows aligned with flux direction
glyph.ScaleArray = ['POINTS', 'fscale']           # length ~ |q|^0.2 (compressed)
glyph.ScaleFactor = 8.6e4
glyph.GlyphMode = 'Uniform Spatial Distribution (Volume Sampling)'
glyph.MaximumNumberOfSamplePoints = 5000
gdisp = Show(glyph, view)
gdisp.ColorArrayName = ['POINTS', '']             # solid black
gdisp.AmbientColor = [0.0, 0.0, 0.0]
gdisp.DiffuseColor = [0.0, 0.0, 0.0]
gdisp.LineWidth = 1.5

# ----------------------------------------------------------------------------
# Town markers + labels (positions in the mesh local frame; z is the surface
# elevation, scaled by ZEX and lifted so the marker sits on the topography).
# ----------------------------------------------------------------------------
TOWN_LIFT = 4000.0
towns = ProgrammableSource()
towns.OutputDataSetType = 'vtkPolyData'
towns.Script = """
import vtk
data = [(168269.0, 138329.0, 89.0, 'Hay'),
        (325000.0, 111206.0, 143.9, 'Narrandera'),
        (50820.0, 123357.0, 62.3, 'Balranald')]
pts = vtk.vtkPoints(); verts = vtk.vtkCellArray()
s = vtk.vtkStringArray(); s.SetName('Name')
for x, y, z, nm in data:
    pid = pts.InsertNextPoint(x, y, z * %g + %g)
    verts.InsertNextCell(1); verts.InsertCellPoint(pid)
    s.InsertNextValue(nm)
out = self.GetPolyDataOutput()
out.SetPoints(pts); out.SetVerts(verts); out.GetPointData().AddArray(s)
""" % (ZEX, TOWN_LIFT)

# red sphere markers
tmark = Glyph(Input=towns, GlyphType='Sphere')
tmark.GlyphMode = 'All Points'
tmark.ScaleArray = ['POINTS', 'No scale array']
tmark.ScaleFactor = 3500.0
tmarkD = Show(tmark, view)
tmarkD.ColorArrayName = ['POINTS', '']
tmarkD.DiffuseColor = [0.85, 0.05, 0.05]
tmarkD.AmbientColor = [0.85, 0.05, 0.05]

# names next to the markers (point labels need an active selection); label
# anchors are lifted a bit above the markers so the text sits higher
tlabsrc = Transform(Input=towns)
tlabsrc.Transform.Translate = [0.0, 0.0, 6000.0]
tlab = Show(tlabsrc, view)
tlab.PointSize = 1.0
SetActiveSource(tlabsrc)
# ID-based selection (avoids the numpy-dependent python query selector)
SelectIDs(IDs=[0, 0, 0, 1, 0, 2], FieldType='POINT', Source=tlabsrc)
tlab.SelectionPointLabelVisibility = 1
tlab.SelectionPointFieldDataArrayName = 'Name'
tlab.SelectionPointLabelFontFamily = 'Times'
tlab.SelectionPointLabelFontSize = 30
tlab.SelectionPointLabelBold = 1
tlab.SelectionPointLabelColor = [0.0, 0.0, 0.0]
tlab.SelectionPointLabelJustification = 'Left'

# ----------------------------------------------------------------------------
# Camera + save
# ----------------------------------------------------------------------------
ResetCamera(view)
cx = 0.5 * (XMIN + XMAX)
cy = 0.5 * (YMIN + YMAX)
cz = 0.5 * (-340.0 + 247.0) * ZEX
D = (XMAX - XMIN)
cam = GetActiveCamera()
# oblique aerial from the south-west, looking north-east down onto the plain
# (x = east, y = north, z up)
cam.SetFocalPoint(cx, cy, cz)
cam.SetPosition(cx - 0.8 * D, cy - 1.55 * D, cz + 0.18 * D)   # pulled back, lower, side-on
cam.SetViewUp(0.0, 0.0, 1.0)
view.CameraViewAngle = 26
Render()
os.makedirs(os.path.dirname(OUT), exist_ok=True)
SaveScreenshot(OUT, view, ImageResolution=RES, TransparentBackground=0)
print("wrote", OUT)
